package com.tugasakhir.signserver.service;

import eu.europa.esig.dss.service.crl.OnlineCRLSource;
import eu.europa.esig.dss.service.ocsp.OnlineOCSPSource;
import eu.europa.esig.dss.spi.DSSUtils;
import eu.europa.esig.dss.spi.x509.CommonTrustedCertificateSource;
import eu.europa.esig.dss.validation.CommonCertificateVerifier;


public class CommonCertificateVerifierSingleton {
    private static CommonCertificateVerifier INSTANCE;
    public static CommonCertificateVerifier getInstance() {
        if (INSTANCE == null){
            INSTANCE = new CommonCertificateVerifier();
            INSTANCE.setCheckRevocationForUntrustedChains(true);
            INSTANCE.setCrlSource(new OnlineCRLSource());
            INSTANCE.setOcspSource(new OnlineOCSPSource());

            //CA Public Cert
            CommonTrustedCertificateSource trustedCertSource = new CommonTrustedCertificateSource();
            trustedCertSource.addCertificate(DSSUtils.loadCertificateFromBase64EncodedString(
                    "MIIFNDCCAxygAwIBAgIUIjNzs++GZW0xJjidUkTPWOyW8+cwDQYJKoZIhvcNAQELBQAwMjELMAkGA1UEBhMCSUQxETAPBgNVBAoMCENsb3VkSVRCMRAwDgYDVQQDDAdDbG91ZENBMB4XDTI0MDQzMDA2NDg1NVoXDTI5MDQyOTA2NDg1NFowMjELMAkGA1UEBhMCSUQxETAPBgNVBAoMCENsb3VkSVRCMRAwDgYDVQQDDAdDbG91ZENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtRR+l1Vjo28qePE+0AZ/DNG7Mv976f6aCgF+wslzoViu+UZT1s+8mOwpz17uXdvqigv0Af1C4W2n81RM9EZ74MnHsYkHg/MwVj/oia7vMCW+FEtxB5WUmUYzqjqnjePQEB6AbBYOcnw7s6h/HzN4U5AkEEzBhCjCYWhQFU4rLtZVl75CIm5tz0t4ZqqBydvWU7+GrS2OSGUi1qEOm13kvITCJ3DhTx6rsm9ADg/ZVzNA77h6UrP1OFhCJtsf31u7SRyep389wcqD+ixVTmmhsAUZGRSOntkCa9zBsIm6DiEufDvMHHr8XkFsGO1dSHgJb0NfK5J8NcOzWO58MEE20QXMFlCiv6vJQ+DmuSuCp9ZaeSoYDhIyC+qosfjsdeF7ODH2CBgF7srYaGt9Ie1KbJVrGOmKUS2Zs5TUSSn6SlYN0s+O8+LsBZ8MMYn7yJUTVrgcIEZJ6ibLIGwe4AXxJMhMWgRszbMaLR05yTtCe634ryCDnsihizveDJLdtXU5l3pXxl+ljThEd8GePQpR0C9qYHdAvvZHKmIGrRyGWGn2q68A9ayZFrnVc/0FclN+9lzyrcfExxoGdbgnUrwGwGXy7T4lp+xQOw8U+/6MEDZHac2mMIA356RZUsW6bFMazbksjRSThIf/zEpxlKUy1Bgi9sDMaqh2yhnjqw1N37kCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfEuGVllzycasHfyQ61dG7NApXH4wDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUAA4ICAQAvTfvTG31CgasFW/jornnz6ro8c+3OP9sZLltI7yHcVJ8QHa0jm4CZuchdpnqkcpOHjdudO6BsahZ2wmoWV0cwUlkKkZ1F8EdJd2mLNKOEdB/xpTgJeu86pKa5av3JEDYJCkqV14BCwfUb/fxyALYJWsORajOB855P/R+v1O90o9wWt/3bVJwqzZbPwveX855JxTMREOxDVVKJKDUO3Kym5oXVm619VNkrCXPiYVnanFFFeYK6363vXvPSSub6KOLAm/tsxVm+jvKKZqtyJwVqH/URYsomtyN+Dwa2DYtMk+iVDIeCD9QqBopwV8XCBM06JMdomKP1yb/lNwLg2kMbXy9DJ7ZC7vw1uAW2/BUzqL0Ojc2fu8fS7kpiCGFLPZ8FEZqDdWB+Itt2ny02G0Dm5e/ysdRlFRClS3Tj8OY9tEfBKDG117iKAYhlAXfB5V2ZDfEDXrU2oIsRIR6MhVzutZcgoCv7DhKto2oJ9V/2K1QPME1tHuqew8iMioFkloTh91y1sPH7oltVSyUwOW+sNOzRtstBtEo09pHcB+o3nP7UWCKAJvSJgV8XuQ/86S5svJDXbDeyNBQ9fSlYVgbTLKYkff6pN4OeM54i1skS4kGA+JkDsQKFcdWlz+k4TLh9g1bmMnuON+AOkcQ8iTat9d0tXVw7kkCmdcW7ynyGgw=="));

            //TSA Public Cert
            CommonTrustedCertificateSource tspSource = new CommonTrustedCertificateSource();
            tspSource.addCertificate(DSSUtils.loadCertificateFromBase64EncodedString(
                    "MIIIATCCBemgAwIBAgIJAMHphhYNqOmCMA0GCSqGSIb3DQEBDQUAMIGVMREwDwYDVQQKEwhGcmVlIFRTQTEQMA4GA1UECxMHUm9vdCBDQTEYMBYGA1UEAxMPd3d3LmZyZWV0c2Eub3JnMSIwIAYJKoZIhvcNAQkBFhNidXNpbGV6YXNAZ21haWwuY29tMRIwEAYDVQQHEwlXdWVyemJ1cmcxDzANBgNVBAgTBkJheWVybjELMAkGA1UEBhMCREUwHhcNMTYwMzEzMDE1NzM5WhcNMjYwMzExMDE1NzM5WjCCAQkxETAPBgNVBAoTCEZyZWUgVFNBMQwwCgYDVQQLEwNUU0ExdjB0BgNVBA0TbVRoaXMgY2VydGlmaWNhdGUgZGlnaXRhbGx5IHNpZ25zIGRvY3VtZW50cyBhbmQgdGltZSBzdGFtcCByZXF1ZXN0cyBtYWRlIHVzaW5nIHRoZSBmcmVldHNhLm9yZyBvbmxpbmUgc2VydmljZXMxGDAWBgNVBAMTD3d3dy5mcmVldHNhLm9yZzEiMCAGCSqGSIb3DQEJARYTYnVzaWxlemFzQGdtYWlsLmNvbTESMBAGA1UEBxMJV3VlcnpidXJnMQswCQYDVQQGEwJERTEPMA0GA1UECBMGQmF5ZXJuMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtZEEjE5IbzTp3Ahif8I3UWIjaYS4LLEwvv9RfPw4+EvOXGWodNqyYhrgvOfjNWPg7ek0/V+IIxWfB4SICCJ0YMHtiCYXBvQoEzQ1nfu4G9E1P8F5YQrxqMjIZdwA6iOzqJvmvQO6hansgn1gVlkF4i1qWE7ROArhUCgM7jl+mKAS84BGQAeGJEO8B3y5X0Ia8xcS2Wg8223/uvPIululZq5SPUWdYXc0bU2EDieIa3wBxbiQ14ouJ7uo3S+aKBLhV9YvkhxlliVIBp3Nt9Bt4YHeDpVw1m+HIgzii2KKtVkG8+4MIQ9wUej0hYr4uaktCeRq8tnLpb/PrRaM32BEkaSwZgOxFMr3Ax8GXn7u+lPFdfNJDAWdLjLdx2rE1MTHEGg7l/0b5ZG8YQVRhtiPmgORswe2+R7ZVNqjb5rNah4Uqi5K3xdGS1TbGNu2/+MAgCRlRzcENs5Od7rl3m/g8/nW5/++tGHnlOkvsJUfiq5hpBLM6bIQdGNci+MnrhoPa0pkbrD4RjvGO/hFUwQ10Z6AJRHsn2bDSWlS2L7LabCqTUxB9gUV/n3LuJMZzdpZumrqS+POrnGOb8tszX25/FC7FbEvNmWwqjByicLm3UsRHOSLotnv21prmlBgaTNPs09vx64zDws0IIqsgN8yZv3ZBGWHa6LLiY2VBTFbbnsCAwEAAaOCAdswggHXMAkGA1UdEwQCMAAwHQYDVR0OBBYEFG52C3tOT5zhYMptLOknoqKUs3c3MB8GA1UdIwQYMBaAFPpVDYw0ZlFDTPfns6dsla965qSXMAsGA1UdDwQEAwIGwDAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDBjBggrBgEFBQcBAQRXMFUwKgYIKwYBBQUHMAKGHmh0dHA6Ly93d3cuZnJlZXRzYS5vcmcvdHNhLmNydDAnBggrBgEFBQcwAYYbaHR0cDovL3d3dy5mcmVldHNhLm9yZzoyNTYwMDcGA1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly93d3cuZnJlZXRzYS5vcmcvY3JsL3Jvb3RfY2EuY3JsMIHGBgNVHSAEgb4wgbswgbgGAQAwgbIwMwYIKwYBBQUHAgEWJ2h0dHA6Ly93d3cuZnJlZXRzYS5vcmcvZnJlZXRzYV9jcHMuaHRtbDAyBggrBgEFBQcCARYmaHR0cDovL3d3dy5mcmVldHNhLm9yZy9mcmVldHNhX2Nwcy5wZGYwRwYIKwYBBQUHAgIwOxo5RnJlZVRTQSB0cnVzdGVkIHRpbWVzdGFtcGluZyBTb2Z0d2FyZSBhcyBhIFNlcnZpY2UgKFNhYVMpMA0GCSqGSIb3DQEBDQUAA4ICAQClyUTixvrAoU2TCn/QoLFytB/BSDw+lXxoorzZuXZPGpUBYf1yRy1Bpe7Sd3hiA7VCIkD7OibN4XYIe2+xAR30zBniVxqkoFEQlmXpTEb1C9Kt7mrEE34lGyWjnavaRRUV2P+eByCejsILeHT34aDt58AJN/6EozT4syZc7S2O2d9hOWWDZ3/rOCwe47I+bqXwXfMN57n4kAXSUmb2EvOci09tq6bXv7rBljK5Bjcyn1Km8GahDkPqqB+Emmxf4/6LXqIydfaH8gUuUC6mwwdipmjM4Hhx3Y6X4xW7qSniVYmXegoxLOlsUQaxQ3x3nys2GxgoiPPuiiNDdPoGPpVhkmJ/fEMQc5ZdEmCSjroAnoA0Ka4yTPlvBCNU83vKWv3cefeTRqs4i/x58B3JhhJU6mzBKZQQdrg9IFVvO+UTJoN/KHb3gzs3Dnw9QQUjgn1PU0AMciGNdSKf8QxviJOpo6HAxCu0yJjBPfQcf2VztPxWUVlxphCnsNKFfIIlqfsgTqzsouiXGqGvh4hqKuPHL+CgquhCmAp3vvFrkhFUWAkNmCtZRmA3ZOdaCtPRFFS5mG9ni5q2r+hJcDOuOr/U60O3vJ3uaIFZSeZIFYKoLnhSd/IoIQfv45AgDgUIrLjqguolBSdvPJ2io9O0rTi7+IQr2jb8JEgpH1WNwC3R4A=="
            ));

            INSTANCE.setTrustedCertSources(trustedCertSource, tspSource);
        }

        return INSTANCE;
    }
}
